name: Deploy to server
on: push
jobs:
  first_jobs:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.mi_variable}}
    env:
      NAME: pruebaVariable
    steps:
      - name: working dir
        id: step_1
        run: echo "mi_variable=variable entorno" >>  $GITHUB_OUTPUT

      - name: obtener mensaje
        run: echo "${{ steps.step_1.outputs.mi_variable}}"

      - uses: actions/checkout@v4
        with:
          hola: 12

      - name: working dir after action
        run: ls -al
  second_jobs:
    if: ${{ github.ref == 'refs/heads/main'}}
    needs:
      - first_jobs
    runs-on: ubuntu-latest

    env:
      SALIDA: ${{ needs.first_jobs.outputs.salida}}
    steps:
      - uses: actions/checkout@v4
      - name: Hola mundo segundo
        if: false
        run: echo "nuevo saludo $SALIDA"
